export let products=[
    {id:1,category:'mobiles',title:'Samsung',price:20000,image:"../assets/samsungmobile.webp"},
    {id:2,category:'mobiles',title:'Vivo',price:30000,image:"../assets/vivo.webp"},
    {id:3,category:'mobiles',title:'iphone',price:20000,image:"../assets/iphone.webp"},
    {id:4,category:'mobiles',title:'Motorolo',price:30000,image:"../assets/motorola.jpg"},
    {id:5,category:'mobiles',title:'Realmi',price:20000,image:"../assets/realmi.webp"},
    {id:6,category:'mobiles',title:'Google',price:30000,image:"../assets/google.png"},
    {id:7,category:'televisions',title:'LG',price:30000,image:"../assets/lg television.png"},
    {id:8,category:'televisions',title:'ASUS',price:30000,image:"../assets/asus.webp"},
    {id:9,category:'televisions',title:'Croma',price:30000,image:"../assets/croma television.jpg"},
    {id:10,category:'televisions',title:'Infinix',price:30000,image:"../assets/infinix television.jpeg"},
    {id:11,category:'televisions',title:'Hitachi',price:30000,image:"../assets/hitachi television.webp"},
    {id:12,category:'laptops',title:'Dell',price:30000,image:"../assets/dell laptop.jpg"},
    {id:13,category:'laptops',title:'ACER',price:30000,image:"../assets/acer laptop.jpg"},
    {id:14,category:'laptops',title:'Macbook',price:30000,image:"../assets/macbook laptop.jpg"},
    {id:15,category:'laptops',title:'HP',price:30000,image:"../assets/hp-laptop.jpg"},
    {id:16,category:'headsets',title:'Bose',price:30000,image:"../assets/bose headset.webp"},
    {id:17,category:'headsets',title:'Apple',price:30000,image:"../assets/apple headset.webp"},
    {id:18,category:'headsets',title:'Sony',price:30000,image:"../assets/sony headset.webp"},
]